In [1]:
print("this is the first ever pytorch code.")

this is the first ever pytorch code.


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [3]:
## scalars
scalar = torch.tensor(5)
scalar

tensor(5)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

5

In [7]:
vector = torch.tensor([4, 6])
vector

tensor([4, 6])

In [8]:
vector.ndim

1

In [9]:
## matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9841, 0.1805, 0.6065, 0.4272],
        [0.5841, 0.8449, 0.7956, 0.1420],
        [0.6553, 0.9654, 0.1086, 0.6826]])

In [15]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [22]:
## creating a range of tensors and tesors like
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
one_to_hundred_byfive = torch.arange(start=1, end=101, step=5)
one_to_hundred_byfive

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [25]:
## creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
### tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device=None)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [30]:
## datatype
sample_tensor = torch.rand(3, 4)
sample_tensor

tensor([[0.6889, 0.1389, 0.1327, 0.2689],
        [0.0476, 0.9013, 0.8944, 0.8485],
        [0.5550, 0.4727, 0.9328, 0.2571]])

In [33]:
print(f"the data type is{sample_tensor.dtype}, the shape is {sample_tensor.shape}, and device it runs is {sample_tensor.device}")

the data type istorch.float32, the shape is torch.Size([3, 4]), and device it runs is cpu


In [49]:
### manipulating tensors
tensor = (3)
mul_ten = torch.mul(tensor , 5)
add_ten = torch.add(tensor, 10)
print(mul_ten.item(), add_ten.item())

15 13


In [55]:
### matrix multiplication
tensor_one = torch.tensor([1,4,6])
tensor_two = torch.tensor([2,3,5])
mat_mul = torch.matmul(tensor_one, tensor_two)
mat_mul

tensor(44)

In [61]:
# use @ instead of matmul
matmul = tensor_one @ tensor_two
matmul


tensor(44)

In [64]:
tensor_one.T.shape

torch.Size([3])

In [66]:
### finding max, min , mean , sum ...etc
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [74]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [75]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [77]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))